import characterization_structure_theory_multivariate_probability_theorem_canonical_lane_mathlib.GateLemmas
import characterization_structure_theory_multivariate_probability_theorem_canonical_lane_mathlib.FinalTheorem
