import characterization_structure_theory_multivariate_probability_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace characterization_structure_theory_multivariate_probability_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end characterization_structure_theory_multivariate_probability_theorem_canonical_lane_mathlib
end HautevilleHouse
